### ISSUE TITLE
Find override previous SetTable

### ISSUE THREAD

**Issue by pbgc** [astaxie/beedb#2]
Hi!

Nice work!
I tried to use beedb with PostgreSQL but as I'm using case sensitive table names, that in PG are specified in queries inside "" like this:

SELECT id, name FROM "ENTITY_NAME" WHERE ....

I tried to do (working with already existing tables):

type EntityName struct {
    Id        int `PK`
    Tipo_loja string
}
var qr EntityName
orm.SetTable("\"ENTITY_NAME\"").Where("id=?", id).Find(&qr)

But this does not work because Find overrides the SetTable call on the line:

orm.TableName = snakeCasedName(StructName(output))

I think Find should only set the table name if it was not previously done by a call to SetTable
(some kind of similar work would have to be done for the Joins to work)

Thanks

**Comment by astaxie** [comment]
I add a condition,you can try the new release
