### ISSUE TITLE
取出数据不完整

### ISSUE THREAD

**Issue by HugoPresents** [astaxie/beedb#27]
我按照你给的example定义了一个表的结构，但是 Where().Find(&) 之后只有部分字段拿到了值我之前用了goorm然后换到这个也是同样问题，取不出来的字段都是相同的。
求帮助，谢谢~
数据库是mysql

源代码是这样的

```
package main

import (
    "fmt"
    "github.com/astaxie/beedb"
    _ "github.com/mikespook/mymysql/godrv"
    "database/sql"
)

type Category struct {
    Id int
    Parent_id int
    Order_id int
    Nav_display int
    Name string
    Display_name string
    Status int
}

func main() {
    db, err := sql.Open("mymysql", "golog/root/rabbit")
    if err != nil {
        panic(err)
    }
    orm := beedb.New(db)
    var cat Category
    err = orm.Where("id=?", 1).Find(&cat)
    if err != nil {
        fmt.Printf("%v", err)
    }
    fmt.Printf("%v", cat)
}
```

打印出来的结果是

```
{1 0 0 0 cccccccccccccccccc  1}
```

实际上应该是

![QQ 20130422134501](https://f.cloud.github.com/assets/1559200/407714/cbe72e34-ab0f-11e2-8a0d-479f04270390.png)

**Comment by NoahShen** [comment]
命名的问题，变量名NavDisplay 对应列名nav_display，变量名DisplayName 对应 display_name，依此类推。

**Comment by HugoPresents** [comment]
我改成了你说的规则，但是现在仍然只能去除前两个字段的值。我看了下源代码
util.go中的

```
func scanMapIntoStruct(obj interface{}, objMap map[string][]byte) error {
    fmt.Printf("\n###objMap:%v\n", objMap)
    dataStruct := reflect.Indirect(reflect.ValueOf(obj))
    if dataStruct.Kind() != reflect.Struct {
        return errors.New("expected a pointer to a struct")
    }

    for key, data := range objMap {
        fmt.Printf("\n###key:%v\n", key)
        structField := dataStruct.FieldByName(titleCasedName(key))
```

里面的for循环只循环了两次
打印出来是这样的

```
###objMap:map[id:[49] parent_id:[] order_id:[48] nav_display:[50] name:[99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99] display_name:[116 101 115 116] st
atus:[49]]

###key:id

###key:parent_id
```

**Comment by elephantsaunter** [comment]
我碰到过一次，结果是数据库中是float字段，定义时写了int类型，碰到这个float字段时后面的就全取不出来

------------------ 原始邮件 ------------------
发件人: "Rabbit52"; 
发送时间: 2013年4月22日(星期一) 下午5:06
收件人: "astaxie/beedb"; 
主题: Re: [beedb] 取出数据不完整 (#27)

我改成了你说的规则，但是现在仍然只能去除前两个字段的值。我看了下源代码
 util.go中的
 func scanMapIntoStruct(obj interface{}, objMap map[string][]byte) error {     fmt.Printf("\n###objMap:%v\n", objMap)     dataStruct := reflect.Indirect(reflect.ValueOf(obj))     if dataStruct.Kind() != reflect.Struct {         return errors.New("expected a pointer to a struct")     }     for key, data := range objMap {         fmt.Printf("\n###key:%v\n", key)         structField := dataStruct.FieldByName(titleCasedName(key))  
里面的for循环只循环了两次
 打印出来是这样的
 ###objMap:map[id:[49] parent_id:[] order_id:[48] nav_display:[50] name:[99 99 99  99 99 99 99 99 99 99 99 99 99 99 99 99 99 99] display_name:[116 101 115 116] st atus:[49]] ###key:id ###key:parent_id

**Comment by HugoPresents** [comment]
但是我的都是int类型呀
![QQ 20130422171351](https://f.cloud.github.com/assets/1559200/408339/0224b24c-ab2d-11e2-96f0-92abb5d36b4a.png)

**Comment by HugoPresents** [comment]
好吧~我刚才试的是 goorm不是这个
换成 beedb 然后再按照二楼说的改了就OK了，谢谢楼上各位 :)
