### ISSUE TITLE
Syntax errors with UPDATE/Relation does not exist

### ISSUE THREAD

**Issue by cmhobbs** [astaxie/beedb#4]
I've got the following function:

```
func storebin(b SampleBin) {
        db, err := sql.Open("postgres", "user=testuser password=testpassword dbname=testdb2")
        if err != nil {
                panic(err)
        }

        orm := beedb.New(db)
        beedb.OnDebug = true

        orm.Save(&b)
}
```

I'm passing it a struct as defined here:

```
type SampleBin struct {
        Id                   int
        FileName    string
        Description string
        Md5              string
}
```

When I pass a SampleBin to that function, I get the following in stdout:

```
UPDATE `sample_bin` SET `description` = ?, `file_name` = ?, `md5` = ? WHERE `Id`=?                                                                                                                                                     &{0xf8400d8580 sample_bin 0 0 `Id`=? [1]  * Id    ` ? 4}
```

And the following in my postgres logs:

```
2012-07-27 15:20:10 CDT ERROR:  syntax error at or near "`" at character 820                                                                                                                                                           
12-07-27 15:20:10 CDT STATEMENT:  UPDATE `sample_bin` SET `description` = ?, `file_name` = ?, `md5` = ? WHERE `Id`=?   

```

Any idea what might be going wrong?

I'm definitely not 100% sure that this is an issue with beedb, I may just be using it wrong.  I'm very new to Go and just started using beedb a couple of nights ago, so please pardon my ignorance.

Thanks for your time!

EDIT - 

This may or may not related (and may prove it to be my environment), but while trying to run the `pg.go` example (after changing the database authentication information), my postgres logs show the following:

```
2012-07-27 15:28:43 CDT ERROR:  relation "userinfo" does not exist at character 13
2012-07-27 15:28:43 CDT STATEMENT:  INSERT INTO "userinfo" ("departname","created","username") VALUES ($1, $2, $3) RETURNING Uid
2012-07-27 15:28:43 CDT LOG:  could not receive data from client: Connection reset by peer
2012-07-27 15:28:43 CDT LOG:  unexpected EOF on client connection
```

While stdout shows `{0 Test_Add_User Test_Add_Departname 2011-12-12}`

**Comment by cmhobbs** [comment]
Also, I don't think that Postgres uses backticks for quoting identifiers... that may be a MySQL thing?

**Comment by cmhobbs** [comment]
Appending "pg" to beedb.New resolved the first issue.  My sample code is now yielding a similar issue as the pg.go code:

```
2012-07-27 15:44:54 CDT ERROR:  relation "sample_bin" does not exist at character 8
2012-07-27 15:44:54 CDT STATEMENT:  UPDATE "sample_bin" SET "md5" = $1, "file_name" = $2, "description" = $3 WHERE "id"=$4
```

**Comment by cmhobbs** [comment]
One last update:  If I create the table in question (I assumed the table not existing would be the issue), I get the same data in stdout with no errors in my postgres log, but nothing is actually stored in the database.

Sorry for the flurry of updates, I'm just exploring things as I go.  Thanks again!

**Comment by astaxie** [comment]
if you want use pg,you should init orm as follow

```
  orm = beedb.New(db, "pg")
```

you can find the example pg.go

**Comment by astaxie** [comment]
Caution

The structs Name 'UserInfo' will turn into the table name 'user_info', the same as the keyname. If the keyname is 'UserName' will turn into the select colum 'user_name'

**Comment by astaxie** [comment]
current beedb not support create table auto if there is no table

**Comment by cmhobbs** [comment]
Thanks for the responses!
