### ISSUE TITLE
snakeCasedName for primary key

### ISSUE THREAD

**Issue by nexneo** [astaxie/beedb#5]
By convention Model struct field names maps to db names via snakeCasedName method but primary key doesn't follow that pattern in Save  and Insert .

I have just started with Golang so mostly it could be my mistake but...

In `func (orm *Model) Save(output interface{}) error`

``` go
    id := results[strings.ToLower(orm.PrimaryKey)]
    delete(results, strings.ToLower(orm.PrimaryKey))
```

it should be using snakeCasedName instead directly using toLower

In `func (orm *Model) Insert(properties map[string]interface{}) (int64, error)`

``` go
    if orm.ParamIdentifier == "pg" {
        statement = fmt.Sprintf("%v RETURNING %v", statement, orm.PrimaryKey)
        var id int64
        orm.Db.QueryRow(statement, args...).Scan(&id)
        return id, nil
```

here no conversion applied to PrimaryKey so it does not insert without setting PrimaryKey via SetPK

**Comment by astaxie** [comment]
Issue #5
