### ISSUE TITLE
mssql 用不了,连接不报错但是执行没有效果.建议用go-mssqldb(朋友请听进去!鬼知道我经历了什么)

### ISSUE THREAD

**Issue by 0Animal0** [astaxie/beedb#61]
mssql 用不了,连接不报错但是执行没有效果.建议用go-mssqldb(朋友请听进去!鬼知道我经历了什么)

**Comment by astaxie** [comment]
❗️ IMPORTANT: Beedb is being deprecated in favor of Beego.orm ❗️
