### ISSUE TITLE
Query syntax error with Postges

### ISSUE THREAD

**Issue by alecloudenback** [astaxie/beedb#8]
Using the /example/pg.go file with a stock Windows Postgres installation results in the following error (and SQL output):

```
panic: reflect: call of reflect.Value.Set on zero Value

goroutine 1 [running]:
reflect.flag.mustBeAssignable(0x0, 0x575a60)
        C:/Go/src/pkg/reflect/value.go:261 +0x87
reflect.Value.Set(0x0, 0x0, 0x0, 0x4f1290, 0x0, ...)
        C:/Go/src/pkg/reflect/value.go:1191 +0x2b
github.com/astaxie/beedb.(*Model).Save(0x663b88, 0x4eb4e0, 0xf840049700, 0xf840049700, 0x408bdf, ...)
        C:/Users/Alec/Google Drive/Programming/goext/src/github.com/astaxie/beedb/beedb.go:380 +0x4f0
main.insert()
        C:/Users/Alec/Google Drive/Programming/Go/beedb pgtest/beedbtest.go:68 +0xa3
main.main()
        C:/Users/Alec/Google Drive/Programming/Go/beedb pgtest/beedbtest.go:46 +0x186

goroutine 2 [syscall]:
created by runtime.main
        C:/Go/src/pkg/runtime/proc.c:221

goroutine 3 [syscall]:
syscall.Syscall6(0x7fd47042180, 0x5, 0x1fc, 0xf840088c00, 0xf840057308, ...)
        C:/Go/src/pkg/runtime/zsyscall_windows_amd64.c:97 +0x55
syscall.GetQueuedCompletionStatus(0x1fc, 0xf840088c00, 0xf840057308, 0xf840057300, 0xffffffff, ...)
        C:/Go/src/pkg/syscall/zsyscall_windows_amd64.go:490 +0x9e
net.(*resultSrv).Run(0xf840057290, 0x0)
        C:/Go/src/pkg/net/fd_windows.go:107 +0x97
created by net.startServer
        C:/Go/src/pkg/net/fd_windows.go:211 +0x12b

goroutine 4 [select]:
net.(*ioSrv).ProcessRemoteIO(0xf84004f870, 0x0)
        C:/Go/src/pkg/net/fd_windows.go:138 +0x1b5
created by net.startServer
        C:/Go/src/pkg/net/fd_windows.go:216 +0x1ab
```

PG Admin shows the following log:

```
STATEMENT: INSERT INTO "userinfo" ("created","departname","username") VALUES ($1, $2, $3) RETURNING uid [2011-12-12 Test_Add_Departname Test_Add_User]
ERROR: syntax error at or near "Test_Add_Departname" at character 106   
```

And running the generated query manually through the PGAdmin Query editor returns:

```
ERROR:  syntax error at or near "Test_Add_Departname"
LINE 2: [2011-12-12 Test_Add_Departname Test_Add_User]
                    ^

********** Error **********

ERROR: syntax error at or near "Test_Add_Departname"
SQL state: 42601
Character: 106
```

I'm not familiar with the SQL query syntax using '$'. What's the rational behind generating statements like that (just wondering, because like as I alluded to, I'm pretty new to database integrated apps)? 

Also, I tried doing a very similar test using a struct with a string field that did not have a single word string like "Test_Add_User", and am not sure how the Postgres would interpret something like `INSERT INTO "userinfo" ("created","departname","username") VALUES ($1, $2, $3) RETURNING uid   [2011-12-12 Sales and  Service Test_Add_User] because the strings aren't contained within`''`

**Comment by astaxie** [comment]
what's your testcode

**Comment by alecloudenback** [comment]
It's literally the test code in the package examples/pg.go, just with the DB name, username, and password changed to match my database.

**Comment by astaxie** [comment]
i have test examples/pg.go in window xp. it run ok
throw you error code maybe  Test_Add_Departname Test_Add_User what's this ?
maybe the table you setup is error

**Comment by alecloudenback** [comment]
This specific issue was a result of me modifying the code because of another error that arose, without realizing that I caused another issue and wasn't addressing the original. I've opened another issue with the correct issue that I had.
